-- Code Clash: Supabase schema for the Clash feature.
-- Run this in the Supabase SQL editor for the project used by the React app.

create table if not exists public.clash_matches (
  clash_id text primary key,
  creator_id text not null,
  creator_email text,
  difficulty text not null default 'Mixed' check (difficulty in ('Easy', 'Medium', 'Hard', 'Mixed')),
  question_count integer not null default 3 check (question_count in (1, 3, 5)),
  time_limit_minutes integer not null default 30 check (time_limit_minutes in (15, 30, 45, 60)),
  status text not null default 'waiting' check (status in ('waiting', 'active', 'completed', 'cancelled')),
  problem_ids jsonb not null default '[]'::jsonb,
  problem_snapshot jsonb not null default '[]'::jsonb,
  ready_players jsonb not null default '[]'::jsonb,
  notifications jsonb not null default '[]'::jsonb,
  summary jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clash_participants (
  id bigint generated by default as identity primary key,
  clash_id text not null references public.clash_matches(clash_id) on delete cascade,
  user_id text not null,
  email text,
  display_name text not null,
  role text not null default 'challenger',
  ready boolean not null default false,
  stats jsonb not null default '{}'::jsonb,
  joined_at timestamptz not null default now(),
  unique (clash_id, user_id)
);

create table if not exists public.clash_submissions (
  id bigint generated by default as identity primary key,
  clash_id text not null references public.clash_matches(clash_id) on delete cascade,
  user_id text not null,
  problem_id text not null,
  language text,
  status text not null,
  accepted boolean not null default false,
  submitted_at timestamptz not null default now()
);

create table if not exists public.clash_results (
  clash_id text primary key references public.clash_matches(clash_id) on delete cascade,
  winner_user_id text,
  is_draw boolean not null default false,
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.clash_history (
  id bigint generated by default as identity primary key,
  clash_id text not null references public.clash_matches(clash_id) on delete cascade,
  user_id text not null,
  opponent_name text not null,
  winner_name text not null,
  score text not null,
  duration_seconds integer not null default 0,
  summary jsonb not null default '{}'::jsonb,
  replay_details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (clash_id, user_id)
);

create index if not exists clash_participants_user_idx on public.clash_participants(user_id);
create index if not exists clash_submissions_match_idx on public.clash_submissions(clash_id, submitted_at desc);
create index if not exists clash_history_user_idx on public.clash_history(user_id, created_at desc);

alter table public.clash_matches replica identity full;
alter table public.clash_participants replica identity full;
alter table public.clash_submissions replica identity full;

-- Enable row level security when policies are ready for production.
-- The current frontend expects authenticated users to read Clash rows by invite link
-- and write their own participant/submission rows.