-- Code Clash Supabase schema.
-- Run this whole file in the Supabase SQL Editor for a fresh project.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  email text not null unique,
  "displayName" text,
  name text,
  profession text,
  institute text,
  age text,
  reason text,
  experience text,
  level text,
  points integer not null default 0,
  aipoints integer not null default 100,
  "likedProblems" text[] not null default '{}',
  "dislikedProblems" text[] not null default '{}',
  "starredProblems" text[] not null default '{}',
  "solvedProblems" text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  display_name text,
  avatar_url text,
  points integer not null default 0,
  strengths jsonb not null default '[]'::jsonb,
  weaknesses jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.problems (
  id text primary key,
  title text not null,
  difficulty text not null check (difficulty in ('Easy', 'Medium', 'Hard')),
  category text not null default 'General',
  "order" integer not null unique,
  "problem_statement" text not null,
  description text,
  examples jsonb not null default '[]'::jsonb,
  testcases jsonb not null default '[]'::jsonb,
  constraints text,
  "starterCode" text,
  "handlerFunction" text,
  "videoId" text,
  likes integer not null default 0,
  dislikes integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contests (
  id bigint generated by default as identity primary key,
  "contestName" text not null,
  duration text,
  uemail text,
  "organizationType" text,
  "organizationName" text,
  questions jsonb not null default '[]'::jsonb,
  "startTime" timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.contestusers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.hostcontests (
  id bigint generated by default as identity primary key,
  name text not null,
  "startTime" timestamptz,
  "endTime" timestamptz,
  duration text,
  "organizationName" text,
  "organizationType" text,
  "numberOfQuestions" integer not null default 0,
  uemail text,
  questions jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.clash_matches (
  clash_id text primary key,
  creator_id text not null,
  creator_email text,
  difficulty text not null default 'Mixed' check (difficulty in ('Easy', 'Medium', 'Hard', 'Mixed')),
  question_count integer not null default 3 check (question_count in (1, 3, 5)),
  time_limit_minutes integer not null default 30 check (time_limit_minutes in (15, 30, 45, 60)),
  status text not null default 'waiting' check (status in ('waiting', 'active', 'completed', 'cancelled')),
  problem_ids jsonb not null default '[]'::jsonb,
  problem_snapshot jsonb not null default '[]'::jsonb,
  ready_players jsonb not null default '[]'::jsonb,
  notifications jsonb not null default '[]'::jsonb,
  summary jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invite_links (
  id bigint generated by default as identity primary key,
  clash_id text not null references public.clash_matches(clash_id) on delete cascade,
  created_by text not null,
  invite_token text not null unique,
  expires_at timestamptz,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.clash_participants (
  id bigint generated by default as identity primary key,
  clash_id text not null references public.clash_matches(clash_id) on delete cascade,
  user_id text not null,
  email text,
  display_name text not null,
  role text not null default 'challenger' check (role in ('creator', 'challenger')),
  ready boolean not null default false,
  stats jsonb not null default '{}'::jsonb,
  joined_at timestamptz not null default now(),
  unique (clash_id, user_id)
);

create table if not exists public.clash_submissions (
  id bigint generated by default as identity primary key,
  clash_id text not null references public.clash_matches(clash_id) on delete cascade,
  user_id text not null,
  problem_id text not null,
  language text,
  status text not null,
  accepted boolean not null default false,
  submitted_at timestamptz not null default now()
);

create table if not exists public.clash_results (
  clash_id text primary key references public.clash_matches(clash_id) on delete cascade,
  winner_user_id text,
  is_draw boolean not null default false,
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.clash_history (
  id bigint generated by default as identity primary key,
  clash_id text not null references public.clash_matches(clash_id) on delete cascade,
  user_id text not null,
  opponent_name text not null,
  winner_name text not null,
  score text not null,
  duration_seconds integer not null default 0,
  summary jsonb not null default '{}'::jsonb,
  replay_details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (clash_id, user_id)
);

create index if not exists problems_order_idx on public.problems("order");
create index if not exists profiles_email_idx on public.profiles(email);
create index if not exists users_email_idx on public.users(email);
create index if not exists invite_links_clash_idx on public.invite_links(clash_id);
create index if not exists invite_links_token_idx on public.invite_links(invite_token);
create index if not exists clash_participants_user_idx on public.clash_participants(user_id);
create index if not exists clash_submissions_match_idx on public.clash_submissions(clash_id, submitted_at desc);
create index if not exists clash_history_user_idx on public.clash_history(user_id, created_at desc);

alter table public.clash_matches replica identity full;
alter table public.clash_participants replica identity full;
alter table public.clash_submissions replica identity full;
alter table public.clash_results replica identity full;
alter table public.clash_history replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.clash_matches;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.clash_participants;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.clash_submissions;
exception
  when duplicate_object then null;
end $$;

alter table public.users enable row level security;
alter table public.profiles enable row level security;
alter table public.problems enable row level security;
alter table public.contests enable row level security;
alter table public.contestusers enable row level security;
alter table public.hostcontests enable row level security;
alter table public.clash_matches enable row level security;
alter table public.invite_links enable row level security;
alter table public.clash_participants enable row level security;
alter table public.clash_submissions enable row level security;
alter table public.clash_results enable row level security;
alter table public.clash_history enable row level security;

drop policy if exists "Users can read own profile" on public.users;
create policy "Users can read own profile" on public.users
  for select to authenticated
  using (user_id = auth.uid() or email = auth.email());

drop policy if exists "Users can insert own profile" on public.users;
create policy "Users can insert own profile" on public.users
  for insert to authenticated
  with check (user_id = auth.uid() or email = auth.email());

drop policy if exists "Users can update own profile" on public.users;
create policy "Users can update own profile" on public.users
  for update to authenticated
  using (user_id = auth.uid() or email = auth.email())
  with check (user_id = auth.uid() or email = auth.email());

drop policy if exists "Profiles are readable" on public.profiles;
create policy "Profiles are readable" on public.profiles
  for select to authenticated
  using (true);

drop policy if exists "Users can insert own profile row" on public.profiles;
create policy "Users can insert own profile row" on public.profiles
  for insert to authenticated
  with check (id = auth.uid());

drop policy if exists "Users can update own profile row" on public.profiles;
create policy "Users can update own profile row" on public.profiles
  for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

drop policy if exists "Problems are readable" on public.problems;
create policy "Problems are readable" on public.problems
  for select to anon, authenticated
  using (true);

drop policy if exists "Authenticated users can update problem counters" on public.problems;
create policy "Authenticated users can update problem counters" on public.problems
  for update to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated contest access" on public.contests;
create policy "Authenticated contest access" on public.contests
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated contest user access" on public.contestusers;
create policy "Authenticated contest user access" on public.contestusers
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated host contest access" on public.hostcontests;
create policy "Authenticated host contest access" on public.hostcontests
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated users can read clashes" on public.clash_matches;
create policy "Authenticated users can read clashes" on public.clash_matches
  for select to authenticated
  using (true);

drop policy if exists "Creators can create clashes" on public.clash_matches;
create policy "Creators can create clashes" on public.clash_matches
  for insert to authenticated
  with check (creator_id = auth.uid()::text);

drop policy if exists "Participants can update clashes" on public.clash_matches;
create policy "Participants can update clashes" on public.clash_matches
  for update to authenticated
  using (
    creator_id = auth.uid()::text
    or exists (
      select 1 from public.clash_participants p
      where p.clash_id = clash_matches.clash_id
        and p.user_id = auth.uid()::text
    )
  )
  with check (true);

drop policy if exists "Authenticated users can read invite links" on public.invite_links;
create policy "Authenticated users can read invite links" on public.invite_links
  for select to authenticated
  using (true);

drop policy if exists "Creators can create invite links" on public.invite_links;
create policy "Creators can create invite links" on public.invite_links
  for insert to authenticated
  with check (created_by = auth.uid()::text);

drop policy if exists "Participants can update invite links" on public.invite_links;
create policy "Participants can update invite links" on public.invite_links
  for update to authenticated
  using (
    created_by = auth.uid()::text
    or exists (
      select 1 from public.clash_participants p
      where p.clash_id = invite_links.clash_id
        and p.user_id = auth.uid()::text
    )
  )
  with check (true);

drop policy if exists "Authenticated users can read clash participants" on public.clash_participants;
create policy "Authenticated users can read clash participants" on public.clash_participants
  for select to authenticated
  using (true);

drop policy if exists "Users can join as themselves" on public.clash_participants;
create policy "Users can join as themselves" on public.clash_participants
  for insert to authenticated
  with check (user_id = auth.uid()::text);

drop policy if exists "Users can update own clash participant row" on public.clash_participants;
create policy "Users can update own clash participant row" on public.clash_participants
  for update to authenticated
  using (user_id = auth.uid()::text)
  with check (user_id = auth.uid()::text);

drop policy if exists "Authenticated users can read clash submissions" on public.clash_submissions;
create policy "Authenticated users can read clash submissions" on public.clash_submissions
  for select to authenticated
  using (true);

drop policy if exists "Users can insert own clash submissions" on public.clash_submissions;
create policy "Users can insert own clash submissions" on public.clash_submissions
  for insert to authenticated
  with check (user_id = auth.uid()::text);

drop policy if exists "Authenticated users can read clash results" on public.clash_results;
create policy "Authenticated users can read clash results" on public.clash_results
  for select to authenticated
  using (true);

drop policy if exists "Participants can write clash results" on public.clash_results;
create policy "Participants can write clash results" on public.clash_results
  for insert to authenticated
  with check (
    exists (
      select 1 from public.clash_participants p
      where p.clash_id = clash_results.clash_id
        and p.user_id = auth.uid()::text
    )
  );

drop policy if exists "Participants can update clash results" on public.clash_results;
create policy "Participants can update clash results" on public.clash_results
  for update to authenticated
  using (
    exists (
      select 1 from public.clash_participants p
      where p.clash_id = clash_results.clash_id
        and p.user_id = auth.uid()::text
    )
  )
  with check (true);

drop policy if exists "Users can read own history and leaderboard rows" on public.clash_history;
create policy "Users can read own history and leaderboard rows" on public.clash_history
  for select to authenticated
  using (true);

drop policy if exists "Participants can insert clash history" on public.clash_history;
create policy "Participants can insert clash history" on public.clash_history
  for insert to authenticated
  with check (
    exists (
      select 1 from public.clash_participants p
      where p.clash_id = clash_history.clash_id
        and p.user_id = auth.uid()::text
    )
  );

drop policy if exists "Participants can update clash history" on public.clash_history;
create policy "Participants can update clash history" on public.clash_history
  for update to authenticated
  using (
    exists (
      select 1 from public.clash_participants p
      where p.clash_id = clash_history.clash_id
        and p.user_id = auth.uid()::text
    )
  )
  with check (true);

insert into public.problems
  (id, title, difficulty, category, "order", "problem_statement", description, examples, testcases, constraints, "starterCode", "videoId")
values
  (
    'two-sum',
    'Two Sum',
    'Easy',
    'Array',
    1,
    '<p>Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.</p>',
    'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.',
    '[{"id":1,"inputText":"nums = [2,7,11,15], target = 9","outputText":"[0,1]","explanation":"nums[0] + nums[1] == 9"}]'::jsonb,
    '[{"input":["4","2 7 11 15","9"],"output":["0 1"]}]'::jsonb,
    '<li>2 <= nums.length <= 10^4</li><li>Only one valid answer exists.</li>',
    '// Write your solution here',
    null
  ),
  (
    'valid-parentheses',
    'Valid Parentheses',
    'Easy',
    'Stack',
    2,
    '<p>Given a string s containing brackets, determine if the input string is valid.</p>',
    'Given a string s containing brackets, determine if the input string is valid.',
    '[{"id":1,"inputText":"s = ()[]{}","outputText":"true"}]'::jsonb,
    '[{"input":["()[]{}"],"output":["true"]}]'::jsonb,
    '<li>1 <= s.length <= 10^4</li>',
    '// Write your solution here',
    null
  ),
  (
    'search-a-2d-matrix',
    'Search a 2D Matrix',
    'Medium',
    'Binary Search',
    3,
    '<p>Write an efficient algorithm that searches for a target value in an m x n integer matrix.</p>',
    'Write an efficient algorithm that searches for a target value in an m x n integer matrix.',
    '[{"id":1,"inputText":"matrix = [[1,3,5],[7,9,11]], target = 9","outputText":"true"}]'::jsonb,
    '[{"input":["2 3","1 3 5","7 9 11","9"],"output":["true"]}]'::jsonb,
    '<li>m == matrix.length</li><li>n == matrix[i].length</li>',
    '// Write your solution here',
    null
  ),
  (
    'jump-game',
    'Jump Game',
    'Medium',
    'Dynamic Programming',
    4,
    '<p>You are given an integer array nums. Return true if you can reach the last index.</p>',
    'You are given an integer array nums. Return true if you can reach the last index.',
    '[{"id":1,"inputText":"nums = [2,3,1,1,4]","outputText":"true"}]'::jsonb,
    '[{"input":["5","2 3 1 1 4"],"output":["true"]}]'::jsonb,
    '<li>1 <= nums.length <= 10^4</li>',
    '// Write your solution here',
    null
  ),
  (
    'reverse-linked-list',
    'Reverse Linked List',
    'Hard',
    'Linked List',
    5,
    '<p>Given the head of a singly linked list, reverse the list and return the reversed list.</p>',
    'Given the head of a singly linked list, reverse the list and return the reversed list.',
    '[{"id":1,"inputText":"head = [1,2,3,4,5]","outputText":"[5,4,3,2,1]"}]'::jsonb,
    '[{"input":["5","1 2 3 4 5"],"output":["5 4 3 2 1"]}]'::jsonb,
    '<li>The number of nodes in the list is in the range [0, 5000].</li>',
    '// Write your solution here',
    null
  )
on conflict (id) do nothing;
