# Generated by Django 4.2.6 on 2025-01-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(help_text='Unique ID for the question', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the question', max_length=255)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], help_text='Difficulty level of the question', max_length=10)),
                ('topics', models.TextField(help_text='Topics related to the question, comma-separated')),
                ('description', models.TextField(help_text='Description of the problem statement')),
                ('examples', models.JSONField(help_text='Example inputs and outputs in JSON format')),
                ('constraints', models.TextField(help_text='Constraints for the problem')),
                ('expected_time_complexity', models.CharField(help_text='Expected time complexity of the solution', max_length=50)),
            ],
        ),
    ]
