# Generated by Django 4.2.6 on 2025-01-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='expected_time_complexity',
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit_per_test',
            field=models.IntegerField(default=1, help_text='Time limit for each testcase'),
            preserve_default=False,
        ),
    ]
