# Generated by Django 4.2.6 on 2025-01-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_question_expected_time_complexity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_limit_per_test',
            field=models.CharField(help_text='Time limit for each testcase', max_length=10),
        ),
    ]
