# Generated by Django 4.2.6 on 2025-01-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_question_time_limit_per_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='examples',
        ),
        migrations.AddField(
            model_name='question',
            name='testcases',
            field=models.JSONField(default=list, help_text='Test cases with inputs and expected outputs in JSON format'),
        ),
    ]
