# Generated by Django 4.2.6 on 2025-01-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_question_examples_question_testcases'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='note',
            field=models.TextField(default='', help_text='Explanation for sample test cases or special Note about question'),
        ),
    ]
