# Generated by Codex on 2026-07-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_question_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clash_id', models.CharField(max_length=32, unique=True)),
                ('creator_id', models.CharField(max_length=255)),
                ('creator_email', models.EmailField(blank=True, max_length=254)),
                ('difficulty', models.CharField(default='Mixed', max_length=10)),
                ('question_count', models.PositiveIntegerField(default=3)),
                ('time_limit_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('problem_ids', models.JSONField(default=list)),
                ('problem_snapshot', models.JSONField(default=list)),
                ('ready_players', models.JSONField(default=list)),
                ('notifications', models.JSONField(default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClashParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('display_name', models.CharField(max_length=255)),
                ('role', models.CharField(default='challenger', max_length=20)),
                ('ready', models.BooleanField(default=False)),
                ('stats', models.JSONField(default=dict)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('clash', models.ForeignKey(db_column='clash_id', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='App.clash', to_field='clash_id')),
            ],
            options={'unique_together': {('clash', 'user_id')}},
        ),
        migrations.CreateModel(
            name='ClashSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('problem_id', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('accepted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('clash', models.ForeignKey(db_column='clash_id', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='App.clash', to_field='clash_id')),
            ],
        ),
        migrations.CreateModel(
            name='ClashResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_draw', models.BooleanField(default=False)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clash', models.OneToOneField(db_column='clash_id', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='App.clash', to_field='clash_id')),
            ],
        ),
        migrations.CreateModel(
            name='ClashHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('opponent_name', models.CharField(max_length=255)),
                ('winner_name', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=40)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(default=dict)),
                ('replay_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clash', models.ForeignKey(db_column='clash_id', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='App.clash', to_field='clash_id')),
            ],
            options={'unique_together': {('clash', 'user_id')}},
        ),
    ]
